include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    - unrelated_type_equality_checks
    - avoid_print
    - depend_on_referenced_packages
    - require_trailing_commas
    - prefer_const_declarations
    - avoid_unused_constructor_parameters
    - public_member_api_docs
    - sort_constructors_first
    - sort_pub_dependencies
    - comment_references
    - unnecessary_lambdas
    - use_build_context_synchronously
    - flutter_style_todos
    - noop_primitive_operations
    - prefer_function_declarations_over_variables
    - lines_longer_than_80_chars
    - prefer_relative_imports
    - directives_ordering
    - avoid_positional_boolean_parameters
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/metrica/models/*"
  errors:
    unrelated_type_equality_checks: error
    unused_local_variable: error
    require_trailing_commas: warning
    prefer_const_declarations: error
    avoid_unused_constructor_parameters: error
    always_use_package_imports: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
    sort_pub_dependencies: ignore
    comment_references: ignore
    unnecessary_lambdas: warning
    use_build_context_synchronously: warning
    unused_import: error
    prefer_relative_imports: error
    directives_ordering: error
    flutter_style_todos: ignore
