name: osk_warehouse
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  collection: ^1.18.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  logger: ^2.0.2+1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  rxdart: ^0.27.7
  uuid: ^4.3.3
  flutter_barcode_scanner: ^2.0.0
  permission_handler: ^11.3.0
  firebase_crashlytics: ^3.4.18
  firebase_analytics: ^10.8.9
  firebase_core: ^2.27.0
  calendar_date_picker2: ^0.5.5
  share_plus: ^7.2.2
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
  mockito: ^5.0.17

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/icons/
    - assets/svg/images/
    - assets/svg/service_icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
