# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup java-version
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Run code generator
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run tests
        run: flutter test
